apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: samplescsharp-polyglot-knative-i0xv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: samplescsharp-polyglot-knative-i0xv
    app.kubernetes.io/part-of: dot-net
  name: samplescsharp-polyglot-knative-i0xv
  namespace: phayes1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: samplescsharp-polyglot-knative-i0xv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: samplescsharp-polyglot-knative-i0xv
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:FgnBp-samplescsharp-polyglot-knative-i0xv
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
